# Generated by Django 5.2.3 on 2025-06-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AudioDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_text", models.CharField(max_length=255)),
                ("input_type", models.CharField(max_length=10)),
                ("description_length", models.CharField(max_length=10)),
                ("description_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user_id", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
